#### Alumno: Néstor Rodríguez Vico

# R Programming Structures

#### Crea una función creciente que indique si los elementos de un vector dado son estrictamente crecientes. No se permite ordenar el vector.

In [1]:
x <- c(1,2,3,4,5,6,7,8,9)
y <- c(1,2,3,4,3,2,1)

creciente <- function(v){
    creciente <- TRUE
    for(i in 2: length(v))
        if(v[i] < v[i-1]){
            creciente <- FALSE
        }
        
    creciente
}


creciente(x)
creciente(y)

[1] TRUE

[1] FALSE

Con apply no se puede hacer, ya que en cada iteración necesitamos el valor actual y el anterior.

#### Crea una función montecarlo que calcule la estimación de la siguiente integral:

$$\int_0^1 x^2 \,dx$$

In [42]:
montecarlo <- function(n){
  hits=0
  for(i in 1:n){
    r1 <- runif(1)
    r2 <- runif(1)
    if(r2 < r1^2)
      hits <- hits + 1
  }
   
  return(hits/n)
}

montecarlo(10000)

[1] 0.334

In [118]:
n <- 10000
r1 <- runif(n)
r2 <- runif(n)
m <- matrix(c(r1*r1, r2), nrow=2, byrow = TRUE)
mayor <- function(x) {
    ifelse(x[2] < x[1], 1, 0)
}
sum(apply(m, 2, mayor)) / n

[1] 0.3319

#### Crea una lista de 5 vectores numéricos y ordena todos los vectores de la lista.

In [3]:
lista <- list(c(3, 4, 5, 1, 2), c(4, 6, 1, 3, 8, 0), c(7, 5, 3, 9, 1, 7))

ordena_listas <- function(l){
    output <- list()
    for(i in 1:length(l)){
        output <- c(output, list(sort(l[[i]])))
    }
    output
}

ordena_listas(lista)

[[1]]
[1] 1 2 3 4 5

[[2]]
[1] 0 1 3 4 6 8

[[3]]
[1] 1 3 5 7 7 9

In [4]:
lista <- list(c(3, 4, 5, 1, 2), c(4, 6, 1, 3, 8, 0), c(7, 5, 3, 9, 1, 7))
lapply(lista, sort)

[[1]]
[1] 1 2 3 4 5

[[2]]
[1] 0 1 3 4 6 8

[[3]]
[1] 1 3 5 7 7 9

#### Calcula el valor mínimo de cada columna de una matriz, pero toma los valores impares como numeros negativos y los pares como positivos.

In [11]:
m <- matrix(1:25, ncol=5, nrow=5)
m

minimos <- function(m){
    nrows = dim(m)[1]
    ncols = dim(m)[2]
    
    min <- rep(0, ncols)
    
    for (i in 1:nrows) {
      for (j in 1:ncols) {
        value = ifelse(m[i,j] %% 2 != 0, 
                       ifelse(m[i,j] > 0, -m[i,j], m[i,j]), 
                       ifelse(m[i,j] > 0, m[i,j], -m[i,j]))
        if(min[j] > value)
            min[j] <- value
      }
    }
    
    min
}

minimos(m)

[,1] [,2] [,3] [,4] [,5]
[1,] 1     6   11   16   21  
[2,] 2     7   12   17   22  
[3,] 3     8   13   18   23  
[4,] 4     9   14   19   24  
[5,] 5    10   15   20   25

[1]  -5  -9 -15 -19 -25

In [26]:
m <- matrix(1:25, ncol=5, nrow=5)
m

get_value <- function(x){
    ifelse(x %% 2 != 0, ifelse(x > 0, -x, x), ifelse(x > 0, x, -x))
}

apply(apply(m, 2, get_value), 2, min)

[,1] [,2] [,3] [,4] [,5]
[1,] 1     6   11   16   21  
[2,] 2     7   12   17   22  
[3,] 3     8   13   18   23  
[4,] 4     9   14   19   24  
[5,] 5    10   15   20   25

[1]  -5  -9 -15 -19 -25

#### Dada una matriz devuelva una lista con los valores mayores a 7 de cada fila.

In [37]:
m <- matrix(1:25, ncol=5, nrow = 5, byrow=TRUE)
m

mayores_que_siete <- function(m){
    nrows = dim(m)[1]
    ncols = dim(m)[2]
    
    min <- rep(list(list()), nrows)
    
    for (i in 1:nrows) {
      for (j in 1:ncols) {
        if(m[i,j] > 7) {
            min[[i]] = c(min[[i]], m[i,j])
        }
      }
    }
    
    min
}

mayores_que_siete(m)

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

[[1]]
list()

[[2]]
[[2]][[1]]
[1] 8

[[2]][[2]]
[1] 9

[[2]][[3]]
[1] 10


[[3]]
[[3]][[1]]
[1] 11

[[3]][[2]]
[1] 12

[[3]][[3]]
[1] 13

[[3]][[4]]
[1] 14

[[3]][[5]]
[1] 15


[[4]]
[[4]][[1]]
[1] 16

[[4]][[2]]
[1] 17

[[4]][[3]]
[1] 18

[[4]][[4]]
[1] 19

[[4]][[5]]
[1] 20


[[5]]
[[5]][[1]]
[1] 21

[[5]][[2]]
[1] 22

[[5]][[3]]
[1] 23

[[5]][[4]]
[1] 24

[[5]][[5]]
[1] 25

In [38]:
m <- matrix(1:25, ncol=5, nrow = 5, byrow=TRUE)
m

mayores_que_siete <- function(x) x[which(x > 7)]
apply(m, 1, mayores_que_siete)

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

[[1]]
integer(0)

[[2]]
[1]  8  9 10

[[3]]
[1] 11 12 13 14 15

[[4]]
[1] 16 17 18 19 20

[[5]]
[1] 21 22 23 24 25